blog_app_blog_post_list:
    path:     /{page}
    defaults: { _controller: BlogAppBlogBundle:Post:list, page: 1 }
    requirements: { page: "\d+" }
blog_app_blog_post_view:
    path:     /view/{id}
    defaults: { _controller: BlogAppBlogBundle:Post:view }
    requirements: { id: "\d+" }
